{
 "title": "ShopFlow Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "P95 Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Orders Created (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(orders_created_total[1m]))",
     "legendFormat": "orders/s"
    }
   ]
  },
  {
   "title": "Payment Duration P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(payment_duration_milliseconds_bucket[5m])) by (le))",
     "legendFormat": "payment p95"
    }
   ]
  }
 ]
}